# Generated by Django 3.1.3 on 2020-11-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olds',
            fields=[
                ('oNo', models.IntegerField(db_column='ONo', primary_key=True, serialize=False)),
                ('oIdentity', models.CharField(db_column='oIdentity', max_length=18)),
                ('oName', models.CharField(db_column='OName', max_length=10)),
                ('oGender', models.CharField(choices=[('男', '男'), ('女', '女')], db_column='oGender', max_length=10)),
                ('oBirthday', models.DateField(db_column='oBirthday')),
                ('oMobile', models.CharField(db_column='oMobile', max_length=11)),
                ('oFamilyMobile', models.CharField(db_column='oFamilyMobile', max_length=11)),
                ('oAddress', models.CharField(db_column='oAddress', max_length=200)),
                ('oImage', models.CharField(db_column='oImage', max_length=200)),
                ('oHealth', models.CharField(db_column='oHealth', max_length=200)),
                ('oSocial', models.CharField(db_column='oSocial', max_length=200)),
            ],
            options={
                'db_table': 'Olds',
                'managed': True,
            },
        ),
    ]
